# Site settings
title: Joseph Spens
email: jpspens@gmail.com
description: My name is Joseph Spens, I am a Full Stack Technical Lead and Architect currently at Quartet in New York City. I'm also the lead organizer of Space Apps NYC.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://josephspens.github.io" # the base hostname & protocol for your site
twitter_username: joespens
github_username: josephspens
stack_overflow_username: 1824448/joseph-spens

# Build settings
markdown: kramdown
exclude: [vendor,bower_components]

# Development
host: 0.0.0.0
